services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracker-api
    environment:
      - ENVIRONMENT=production
      - FLARESOLVERR_URL=${FLARESOLVERR_URL}
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      flaresolverr:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: tracker-api-flaresolverr
    ports:
      - "${PORT:-8191}:8191"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Dublin
    networks:
      - internal

  postgres:
    image: postgres:latest
    container_name: tracker-api-postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: tracker-api-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  internal:
    external: false

volumes:
  postgres_data: {}
